
version: "3.9"
services:
  simpy:
    build: ./simpy-adapter
    image: seh-simpy:latest
    ports: ["7001:7001"]
  mesa:
    build: ./mesa-adapter
    image: seh-mesa:latest
    ports: ["7002:7002"]
  epinow2:
    build: ./epinow2-adapter
    image: seh-epinow2:latest
    ports: ["7003:7003"]
  anylogic:
    build: ../anylogic-adapter/docker
    image: anylogic-pypeline:latest
    ports: ["7004:7004"]
    environment:
      - PYTHONUNBUFFERED=1
      - ML_MODELS_PATH=/app/python_scripts
