"""
Insight Router

Manage and query AI-generated insights
"""

import sys
from pathlib import Path
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field, ConfigDict
from typing import Optional, List
from sqlalchemy.orm import Session
from datetime import datetime

# Add shared to path
shared_path = Path(__file__).parent.parent.parent / "shared"
sys.path.insert(0, str(shared_path))

from database.base import get_db

router = APIRouter()


# Pydantic schemas
class InsightCreate(BaseModel):
    """Create insight"""
    model_config = ConfigDict(from_attributes=True)

    organ_name: str
    insight_type: str
    content: str
    confidence: float
    twin_id: Optional[int] = None
    metadata: dict = Field(default_factory=dict)
    tenant_id: Optional[str] = None


class InsightResponse(BaseModel):
    """Insight response"""
    model_config = ConfigDict(from_attributes=True)

    id: int
    organ_name: str
    insight_type: str
    content: str
    confidence: float
    twin_id: Optional[int]
    metadata: dict
    created_at: str


class InsightQuery(BaseModel):
    """Query insights"""
    model_config = ConfigDict(from_attributes=True)

    organ_name: Optional[str] = None
    insight_type: Optional[str] = None
    twin_id: Optional[int] = None
    min_confidence: Optional[float] = None
    limit: int = Field(default=50, le=200)


# TODO: These endpoints need actual database models
# For now, returning mock responses


@router.post("/insights", response_model=InsightResponse, status_code=201)
async def create_insight(
    insight: InsightCreate,
    db: Session = Depends(get_db)
):
    """
    Create new insight

    Insights are discrete, actionable intelligence items generated by organs
    """
    # TODO: Save to database

    return InsightResponse(
        id=1,
        organ_name=insight.organ_name,
        insight_type=insight.insight_type,
        content=insight.content,
        confidence=insight.confidence,
        twin_id=insight.twin_id,
        metadata=insight.metadata,
        created_at=datetime.utcnow().isoformat()
    )


@router.post("/insights/query", response_model=List[InsightResponse])
async def query_insights(
    query: InsightQuery,
    db: Session = Depends(get_db)
):
    """
    Query insights with filters

    Useful for:
    - Finding all insights from a specific organ
    - Getting high-confidence insights only
    - Retrieving insights for a specific Digital Twin
    """
    # TODO: Query database

    # Mock response
    return []


@router.get("/insights/{insight_id}", response_model=InsightResponse)
async def get_insight(
    insight_id: int,
    db: Session = Depends(get_db)
):
    """Get specific insight by ID"""
    # TODO: Query database

    raise HTTPException(status_code=404, detail="Insight not found")


@router.delete("/insights/{insight_id}")
async def delete_insight(
    insight_id: int,
    db: Session = Depends(get_db)
):
    """Delete insight"""
    # TODO: Delete from database

    return {"message": "Insight deleted"}


@router.get("/insights/stats/summary")
async def insights_summary(
    twin_id: Optional[int] = None,
    db: Session = Depends(get_db)
):
    """
    Get insights summary statistics

    Returns aggregated stats on insights by organ, type, confidence
    """
    # TODO: Query database for stats

    return {
        "total_insights": 0,
        "by_organ": {},
        "by_type": {},
        "average_confidence": 0.0,
        "high_confidence_count": 0,
        "recent_insights": 0
    }
