#!/usr/bin/env python3
"""
Code Generator - AI-powered and template-based code generation
Enhanced with Claude AI for intelligent code creation
"""

import logging
from pathlib import Path
from typing import Dict, List, Any, Optional
from jinja2 import Environment, FileSystemLoader, BaseLoader
import json
import os

logger = logging.getLogger(__name__)

class CodeGenerator:
    """Generates code based on architecture analysis and patterns with AI enhancement"""

    def __init__(self, use_ai: bool = True):
        self.templates = self._load_templates()
        self.use_ai = use_ai
        self.ai_generator = None

        # Initialize AI generator if available
        if use_ai:
            try:
                from ai_integration.claude_generator import ClaudeCodeGenerator
                self.ai_generator = ClaudeCodeGenerator()
                logger.info("✅ AI code generation enabled")
            except ImportError as e:
                logger.warning(f"AI generator not available, falling back to templates: {e}")
                self.use_ai = False

    def _load_templates(self) -> Dict[str, str]:
        """Load code generation templates"""
        return {
            "orchestrator_base": """#!/usr/bin/env python3
\"\"\"
{{ project_name }} - Generated Orchestrator
Architecture: {{ architecture_pattern }}
Generated by Universal Orchestration Platform
\"\"\"

import asyncio
import logging
from typing import Dict, Any, Optional
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class {{ class_name }}Orchestrator:
    \"\"\"{{ description }}\"\"\"

    def __init__(self):
        self.app = FastAPI(
            title="{{ project_name }}",
            description="{{ description }}",
            version="1.0.0"
        )
        self._setup_middleware()
        self._setup_routes()
        self.components = {}

    def _setup_middleware(self):
        \"\"\"Setup FastAPI middleware\"\"\"
        self.app.add_middleware(
            CORSMiddleware,
            allow_origins=["*"],
            allow_credentials=True,
            allow_methods=["*"],
            allow_headers=["*"],
        )

    def _setup_routes(self):
        \"\"\"Setup API routes\"\"\"
{% for endpoint in endpoints %}
        @self.app.{{ endpoint.method.lower() }}("{{ endpoint.path }}")
        async def {{ endpoint.name }}():
            \"\"\"{{ endpoint.description }}\"\"\"
            try:
                # Implementation needed
                return {"status": "success", "message": "{{ endpoint.name }} endpoint"}
            except Exception as e:
                logger.error(f"Error in {{ endpoint.name }}: {e}")
                raise HTTPException(status_code=500, detail=str(e))
{% endfor %}

        @self.app.get("/health")
        async def health_check():
            \"\"\"Health check endpoint\"\"\"
            return {
                "status": "healthy",
                "service": "{{ project_name }}",
                "version": "1.0.0"
            }

    async def start(self):
        \"\"\"Start the orchestrator\"\"\"
        logger.info("Starting {{ project_name }} Orchestrator...")
        # Initialize components
        await self._initialize_components()
        logger.info("{{ project_name }} Orchestrator started successfully")

    async def _initialize_components(self):
        \"\"\"Initialize orchestrator components\"\"\"
{% for component in components %}
        # Initialize {{ component.name }}
        self.components["{{ component.name }}"] = {{ component.init_code }}
{% endfor %}

    async def stop(self):
        \"\"\"Stop the orchestrator\"\"\"
        logger.info("Stopping {{ project_name }} Orchestrator...")
        # Cleanup components
        for component in self.components.values():
            if hasattr(component, 'stop'):
                await component.stop()

if __name__ == "__main__":
    import uvicorn
    orchestrator = {{ class_name }}Orchestrator()

    uvicorn.run(
        orchestrator.app,
        host="0.0.0.0",
        port=8000,
        log_level="info"
    )
""",

            "microservice_template": """#!/usr/bin/env python3
\"\"\"
{{ service_name }} Microservice
Part of {{ project_name }} system
\"\"\"

import asyncio
import logging
from typing import Dict, Any, Optional
from fastapi import FastAPI, HTTPException, Depends
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

logger = logging.getLogger(__name__)

# Data models
{% for model in data_models %}
class {{ model.name }}(BaseModel):
{% for field in model.fields %}
    {{ field.name }}: {{ field.type }}{{ " = " + field.default if field.default else "" }}
{% endfor %}
{% endfor %}

class {{ service_class }}Service:
    \"\"\"{{ service_description }}\"\"\"

    def __init__(self):
        self.app = FastAPI(
            title="{{ service_name }}",
            description="{{ service_description }}",
            version="1.0.0"
        )
        self._setup_middleware()
        self._setup_routes()

    def _setup_middleware(self):
        self.app.add_middleware(
            CORSMiddleware,
            allow_origins=["*"],
            allow_credentials=True,
            allow_methods=["*"],
            allow_headers=["*"],
        )

    def _setup_routes(self):
{% for endpoint in service_endpoints %}
        @self.app.{{ endpoint.method.lower() }}("{{ endpoint.path }}")
        async def {{ endpoint.function_name }}({{ endpoint.params }}):
            \"\"\"{{ endpoint.description }}\"\"\"
            try:
                # TODO: Implement {{ endpoint.function_name }}
                return {"message": "{{ endpoint.function_name }} implementation needed"}
            except Exception as e:
                logger.error(f"Error in {{ endpoint.function_name }}: {e}")
                raise HTTPException(status_code=500, detail=str(e))
{% endfor %}

        @self.app.get("/health")
        async def health():
            return {"status": "healthy", "service": "{{ service_name }}"}

if __name__ == "__main__":
    import uvicorn
    service = {{ service_class }}Service()

    uvicorn.run(
        service.app,
        host="0.0.0.0",
        port={{ service_port }},
        log_level="info"
    )
""",

            "docker_compose": """version: '3.8'

services:
{% for service in services %}
  {{ service.name }}:
    build:
      context: ./{{ service.path }}
      dockerfile: Dockerfile
    ports:
      - "{{ service.port }}:{{ service.internal_port }}"
    environment:
{% for env_var in service.environment %}
      - {{ env_var.name }}={{ env_var.value }}
{% endfor %}
    depends_on:
{% for dep in service.dependencies %}
      - {{ dep }}
{% endfor %}
    networks:
      - {{ project_name }}_network
{% if service.volumes %}
    volumes:
{% for volume in service.volumes %}
      - {{ volume }}
{% endfor %}
{% endif %}

{% endfor %}
{% if has_database %}
  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB={{ db_name }}
      - POSTGRES_USER={{ db_user }}
      - POSTGRES_PASSWORD={{ db_password }}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - {{ project_name }}_network
{% endif %}

{% if has_redis %}
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - {{ project_name }}_network
{% endif %}

networks:
  {{ project_name }}_network:
    driver: bridge

{% if has_database %}
volumes:
  postgres_data:
{% endif %}
""",

            "kubernetes_deployment": """apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ service_name }}-deployment
  labels:
    app: {{ service_name }}
spec:
  replicas: {{ replicas }}
  selector:
    matchLabels:
      app: {{ service_name }}
  template:
    metadata:
      labels:
        app: {{ service_name }}
    spec:
      containers:
      - name: {{ service_name }}
        image: {{ image_name }}:{{ image_tag }}
        ports:
        - containerPort: {{ container_port }}
        env:
{% for env_var in environment_variables %}
        - name: {{ env_var.name }}
          value: "{{ env_var.value }}"
{% endfor %}
        resources:
          requests:
            memory: "{{ memory_request }}"
            cpu: "{{ cpu_request }}"
          limits:
            memory: "{{ memory_limit }}"
            cpu: "{{ cpu_limit }}"
        livenessProbe:
          httpGet:
            path: /health
            port: {{ container_port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: {{ container_port }}
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: {{ service_name }}-service
spec:
  selector:
    app: {{ service_name }}
  ports:
    - protocol: TCP
      port: {{ service_port }}
      targetPort: {{ container_port }}
  type: ClusterIP
""",

            "dockerfile": """FROM python:3.11-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \\
    gcc \\
    && rm -rf /var/lib/apt/lists/*

# Copy requirements first for better caching
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Create non-root user
RUN useradd -m -u 1000 appuser && chown -R appuser:appuser /app
USER appuser

# Expose port
EXPOSE {{ port }}

# Health check
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \\
    CMD curl -f http://localhost:{{ port }}/health || exit 1

# Run application
CMD ["python", "{{ main_file }}"]
"""
        }

    async def generate(self, architecture: Dict[str, Any]) -> Dict[str, str]:
        """Generate code based on architecture analysis with AI enhancement"""
        try:
            logger.info("🚀 Starting AI-enhanced code generation")

            # Try AI generation first if available
            if self.use_ai and self.ai_generator:
                try:
                    logger.info("🤖 Using AI code generation")
                    ai_generated_files = await self.ai_generator.generate_intelligent_code(architecture)

                    # Add AI explanation
                    explanation = await self.ai_generator.explain_architecture_decisions(architecture)
                    ai_generated_files["ARCHITECTURE_EXPLANATION.md"] = explanation

                    logger.info(f"✅ AI generated {len(ai_generated_files)} files")
                    return ai_generated_files

                except Exception as e:
                    logger.warning(f"AI generation failed, falling back to templates: {e}")
                    # Continue with template generation below

            # Fallback to template-based generation
            logger.info("📝 Using template-based generation")
            generated_files = {}
            pattern = architecture.get("primary_pattern", "monolith")

            if pattern == "monolith":
                files = self._generate_monolith(architecture)
            elif pattern == "microservices":
                files = self._generate_microservices(architecture)
            elif pattern == "serverless":
                files = self._generate_serverless(architecture)
            else:
                files = self._generate_hybrid(architecture)

            generated_files.update(files)

            # Generate common infrastructure files
            infrastructure_files = self._generate_infrastructure(architecture)
            generated_files.update(infrastructure_files)

            logger.info(f"✅ Template generated {len(generated_files)} files")
            return generated_files

        except Exception as e:
            logger.error(f"❌ Code generation failed: {e}")
            raise

    def _generate_monolith(self, architecture: Dict[str, Any]) -> Dict[str, str]:
        """Generate monolith architecture code"""
        files = {}

        # Main orchestrator
        template_vars = {
            "project_name": "MonolithApp",
            "class_name": "Main",
            "description": "Monolithic application orchestrator",
            "architecture_pattern": "monolith",
            "endpoints": [
                {
                    "method": "GET",
                    "path": "/api/users",
                    "name": "get_users",
                    "description": "Get all users"
                },
                {
                    "method": "POST",
                    "path": "/api/users",
                    "name": "create_user",
                    "description": "Create new user"
                }
            ],
            "components": [
                {
                    "name": "database",
                    "init_code": "DatabaseConnection()"
                },
                {
                    "name": "auth",
                    "init_code": "AuthenticationService()"
                }
            ]
        }

        files["main.py"] = self._render_template("orchestrator_base", template_vars)

        # Add requirements.txt
        files["requirements.txt"] = """fastapi==0.104.1
uvicorn==0.24.0
pydantic==2.5.0
sqlalchemy==2.0.23
redis==5.0.1
pytest==7.4.3
"""

        # Add Dockerfile
        dockerfile_vars = {
            "port": 8000,
            "main_file": "main.py"
        }
        files["Dockerfile"] = self._render_template("dockerfile", dockerfile_vars)

        return files

    def _generate_microservices(self, architecture: Dict[str, Any]) -> Dict[str, str]:
        """Generate microservices architecture code"""
        files = {}

        # Generate API Gateway
        gateway_vars = {
            "project_name": "MicroservicesApp",
            "class_name": "Gateway",
            "description": "API Gateway for microservices",
            "architecture_pattern": "microservices",
            "endpoints": [
                {
                    "method": "GET",
                    "path": "/api/gateway/health",
                    "name": "gateway_health",
                    "description": "Gateway health check"
                }
            ],
            "components": [
                {
                    "name": "load_balancer",
                    "init_code": "LoadBalancer()"
                },
                {
                    "name": "service_discovery",
                    "init_code": "ServiceDiscovery()"
                }
            ]
        }

        files["gateway/main.py"] = self._render_template("orchestrator_base", gateway_vars)

        # Generate individual services
        services = [
            {
                "name": "user_service",
                "class": "User",
                "description": "User management service",
                "port": 8001,
                "endpoints": [
                    {
                        "method": "GET",
                        "path": "/users",
                        "function_name": "get_users",
                        "description": "Get all users",
                        "params": ""
                    }
                ]
            },
            {
                "name": "order_service",
                "class": "Order",
                "description": "Order management service",
                "port": 8002,
                "endpoints": [
                    {
                        "method": "GET",
                        "path": "/orders",
                        "function_name": "get_orders",
                        "description": "Get all orders",
                        "params": ""
                    }
                ]
            }
        ]

        for service in services:
            service_vars = {
                "service_name": service["name"],
                "service_class": service["class"],
                "service_description": service["description"],
                "service_port": service["port"],
                "service_endpoints": service["endpoints"],
                "data_models": [
                    {
                        "name": f"{service['class']}Model",
                        "fields": [
                            {"name": "id", "type": "int", "default": None},
                            {"name": "name", "type": "str", "default": None}
                        ]
                    }
                ]
            }

            files[f"{service['name']}/main.py"] = self._render_template("microservice_template", service_vars)

        # Generate docker-compose
        compose_vars = {
            "project_name": "microservices_app",
            "services": [
                {
                    "name": "gateway",
                    "path": "gateway",
                    "port": 8000,
                    "internal_port": 8000,
                    "environment": [{"name": "ENV", "value": "production"}],
                    "dependencies": ["user_service", "order_service"],
                    "volumes": []
                }
            ] + [
                {
                    "name": service["name"],
                    "path": service["name"],
                    "port": service["port"],
                    "internal_port": service["port"],
                    "environment": [{"name": "ENV", "value": "production"}],
                    "dependencies": [],
                    "volumes": []
                } for service in services
            ],
            "has_database": True,
            "has_redis": True,
            "db_name": "microservices_db",
            "db_user": "postgres",
            "db_password": "password"
        }

        files["docker-compose.yml"] = self._render_template("docker_compose", compose_vars)

        return files

    def _generate_serverless(self, architecture: Dict[str, Any]) -> Dict[str, str]:
        """Generate serverless architecture code"""
        files = {}

        # Serverless functions
        functions = [
            "user_handler",
            "order_handler",
            "auth_handler"
        ]

        for func in functions:
            function_code = f"""#!/usr/bin/env python3
\"\"\"
{func} - Serverless function
\"\"\"

import json
import logging

logger = logging.getLogger(__name__)

def lambda_handler(event, context):
    \"\"\"AWS Lambda handler for {func}\"\"\"
    try:
        # Extract request data
        body = json.loads(event.get('body', '{{}}'))
        method = event.get('httpMethod', 'GET')

        logger.info(f"Processing {{method}} request for {func}")

        # TODO: Implement {func} logic

        return {{
            'statusCode': 200,
            'headers': {{
                'Content-Type': 'application/json',
                'Access-Control-Allow-Origin': '*'
            }},
            'body': json.dumps({{
                'message': f'{func} function executed successfully',
                'method': method
            }})
        }}

    except Exception as e:
        logger.error(f"Error in {func}: {{e}}")
        return {{
            'statusCode': 500,
            'headers': {{
                'Content-Type': 'application/json'
            }},
            'body': json.dumps({{'error': str(e)}})
        }}
"""
            files[f"functions/{func}.py"] = function_code

        # Serverless configuration
        serverless_config = """service: serverless-app

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  stage: ${opt:stage, 'dev'}

functions:
  userHandler:
    handler: functions/user_handler.lambda_handler
    events:
      - http:
          path: /users
          method: ANY
          cors: true

  orderHandler:
    handler: functions/order_handler.lambda_handler
    events:
      - http:
          path: /orders
          method: ANY
          cors: true

  authHandler:
    handler: functions/auth_handler.lambda_handler
    events:
      - http:
          path: /auth
          method: ANY
          cors: true

plugins:
  - serverless-python-requirements
"""
        files["serverless.yml"] = serverless_config

        return files

    def _generate_hybrid(self, architecture: Dict[str, Any]) -> Dict[str, str]:
        """Generate hybrid architecture code"""
        files = {}

        # Combine monolith and microservices approaches
        monolith_files = self._generate_monolith(architecture)
        microservices_files = self._generate_microservices(architecture)

        # Add with prefixes
        for path, content in monolith_files.items():
            files[f"core/{path}"] = content

        for path, content in microservices_files.items():
            if "service" in path:
                files[f"services/{path}"] = content

        return files

    def _generate_infrastructure(self, architecture: Dict[str, Any]) -> Dict[str, str]:
        """Generate infrastructure files"""
        files = {}

        # Kubernetes manifests
        if architecture.get("primary_pattern") == "microservices":
            k8s_vars = {
                "service_name": "api-gateway",
                "image_name": "microservices-app/gateway",
                "image_tag": "latest",
                "replicas": 3,
                "container_port": 8000,
                "service_port": 80,
                "memory_request": "256Mi",
                "cpu_request": "100m",
                "memory_limit": "512Mi",
                "cpu_limit": "500m",
                "environment_variables": [
                    {"name": "ENV", "value": "production"},
                    {"name": "LOG_LEVEL", "value": "info"}
                ]
            }

            files["k8s/gateway-deployment.yaml"] = self._render_template("kubernetes_deployment", k8s_vars)

        # Monitoring configuration
        files["monitoring/prometheus.yml"] = """global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app-metrics'
    static_configs:
      - targets: ['localhost:8000']
"""

        # CI/CD pipeline
        files[".github/workflows/deploy.yml"] = """name: Deploy Application

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Build Docker image
      run: |
        docker build -t app:latest .

    - name: Deploy
      run: |
        echo "Deploy to production"
"""

        return files

    def _render_template(self, template_name: str, variables: Dict[str, Any]) -> str:
        """Render a template with variables"""
        try:
            template_content = self.templates.get(template_name, "")
            if not template_content:
                logger.error(f"Template not found: {template_name}")
                return f"# Template rendering failed: Template '{template_name}' not found"
            env = Environment(loader=BaseLoader())
            template = env.from_string(template_content)
            return template.render(**variables)
        except Exception as e:
            logger.error(f"Template rendering failed: {e}")
            return f"# Template rendering failed: {e}"