#!/usr/bin/env python3
"""
Anthropic Service для MSP Server
Использует официальный SDK Anthropic для AI функций
"""

import asyncio
import logging
from typing import Dict, List, Any, Optional
import json
import os
from datetime import datetime

import anthropic
from anthropic import Anthropic

logger = logging.getLogger(__name__)

class AnthropicService:
    """Сервис для работы с Anthropic Claude API"""

    def __init__(self, api_key: Optional[str] = None):
        """
        Initialize Anthropic service

        Args:
            api_key: Anthropic API key (если не указан, берется из переменной среды)
        """
        self.api_key = api_key or os.getenv("ANTHROPIC_API_KEY")

        if not self.api_key:
            logger.warning("Anthropic API key not provided - AI features will be limited")
            self.client = None
        else:
            self.client = Anthropic(api_key=self.api_key)
            logger.info("Anthropic service initialized successfully")

    async def analyze_project_structure(self, project_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Анализ структуры проекта с помощью Claude

        Args:
            project_data: Данные о проекте для анализа

        Returns:
            Результат анализа от Claude
        """
        if not self.client:
            return {"error": "Anthropic API not available", "mock": True}

        try:
            # Подготовка промпта для анализа
            analysis_prompt = self._prepare_analysis_prompt(project_data)

            message = self.client.messages.create(
                model="claude-3-sonnet-20240229",
                max_tokens=4000,
                temperature=0.1,
                messages=[
                    {
                        "role": "user",
                        "content": analysis_prompt
                    }
                ]
            )

            # Парсинг ответа Claude
            claude_response = message.content[0].text
            analysis_result = self._parse_analysis_response(claude_response)

            logger.info(f"Project analysis completed by Claude")

            return {
                "status": "success",
                "analysis": analysis_result,
                "claude_response": claude_response,
                "timestamp": datetime.now().isoformat(),
                "model": "claude-3-sonnet-20240229"
            }

        except Exception as e:
            logger.error(f"Claude analysis failed: {e}")
            return {
                "status": "error",
                "error": str(e),
                "timestamp": datetime.now().isoformat()
            }

    async def generate_recommendations(self, analysis: Dict[str, Any]) -> Dict[str, Any]:
        """
        Генерация рекомендаций на основе анализа

        Args:
            analysis: Результат анализа проекта

        Returns:
            Рекомендации от Claude
        """
        if not self.client:
            return {"error": "Anthropic API not available", "mock": True}

        try:
            # Подготовка промпта для рекомендаций
            recommendations_prompt = self._prepare_recommendations_prompt(analysis)

            message = self.client.messages.create(
                model="claude-3-sonnet-20240229",
                max_tokens=3000,
                temperature=0.3,
                messages=[
                    {
                        "role": "user",
                        "content": recommendations_prompt
                    }
                ]
            )

            claude_response = message.content[0].text
            recommendations = self._parse_recommendations_response(claude_response)

            logger.info(f"Recommendations generated by Claude")

            return {
                "status": "success",
                "recommendations": recommendations,
                "claude_response": claude_response,
                "timestamp": datetime.now().isoformat(),
                "model": "claude-3-sonnet-20240229"
            }

        except Exception as e:
            logger.error(f"Claude recommendations failed: {e}")
            return {
                "status": "error",
                "error": str(e),
                "timestamp": datetime.now().isoformat()
            }

    async def explain_architecture(self, architecture_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Объяснение архитектуры проекта

        Args:
            architecture_data: Данные об архитектуре

        Returns:
            Объяснение от Claude
        """
        if not self.client:
            return {"error": "Anthropic API not available", "mock": True}

        try:
            explanation_prompt = self._prepare_explanation_prompt(architecture_data)

            message = self.client.messages.create(
                model="claude-3-sonnet-20240229",
                max_tokens=3500,
                temperature=0.2,
                messages=[
                    {
                        "role": "user",
                        "content": explanation_prompt
                    }
                ]
            )

            claude_response = message.content[0].text

            logger.info(f"Architecture explanation generated by Claude")

            return {
                "status": "success",
                "explanation": claude_response,
                "timestamp": datetime.now().isoformat(),
                "model": "claude-3-sonnet-20240229"
            }

        except Exception as e:
            logger.error(f"Claude explanation failed: {e}")
            return {
                "status": "error",
                "error": str(e),
                "timestamp": datetime.now().isoformat()
            }

    async def assess_code_quality(self, code_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Оценка качества кода

        Args:
            code_data: Данные о коде для оценки

        Returns:
            Оценка качества от Claude
        """
        if not self.client:
            return {"error": "Anthropic API not available", "mock": True}

        try:
            quality_prompt = self._prepare_quality_assessment_prompt(code_data)

            message = self.client.messages.create(
                model="claude-3-sonnet-20240229",
                max_tokens=2500,
                temperature=0.1,
                messages=[
                    {
                        "role": "user",
                        "content": quality_prompt
                    }
                ]
            )

            claude_response = message.content[0].text
            quality_assessment = self._parse_quality_response(claude_response)

            logger.info(f"Code quality assessment completed by Claude")

            return {
                "status": "success",
                "assessment": quality_assessment,
                "claude_response": claude_response,
                "timestamp": datetime.now().isoformat(),
                "model": "claude-3-sonnet-20240229"
            }

        except Exception as e:
            logger.error(f"Claude quality assessment failed: {e}")
            return {
                "status": "error",
                "error": str(e),
                "timestamp": datetime.now().isoformat()
            }

    def _prepare_analysis_prompt(self, project_data: Dict[str, Any]) -> str:
        """Подготовка промпта для анализа проекта"""
        return f"""
Проанализируй структуру проекта и предоставь детальный анализ:

Данные проекта:
{json.dumps(project_data, indent=2, ensure_ascii=False)}

Пожалуйста, проанализируй:
1. Архитектурный паттерн проекта
2. Используемые технологии и фреймворки
3. Структуру и организацию кода
4. Потенциальные проблемы и узкие места
5. Уровень сложности проекта
6. Соответствие best practices

Предоставь анализ в структурированном JSON формате с полями:
- architecture_pattern
- technologies
- complexity_level
- issues
- strengths
- recommendations

Ответ должен быть профессиональным и подробным.
"""

    def _prepare_recommendations_prompt(self, analysis: Dict[str, Any]) -> str:
        """Подготовка промпта для генерации рекомендаций"""
        return f"""
На основе анализа проекта сгенерируй конкретные рекомендации по улучшению:

Анализ проекта:
{json.dumps(analysis, indent=2, ensure_ascii=False)}

Предоставь рекомендации по:
1. Улучшению архитектуры
2. Оптимизации производительности
3. Повышению безопасности
4. Улучшению поддерживаемости кода
5. Современным практикам разработки
6. Инструментам и технологиям

Формат ответа: JSON с категориями рекомендаций и конкретными действиями.
Рекомендации должны быть практичными и реализуемыми.
"""

    def _prepare_explanation_prompt(self, architecture_data: Dict[str, Any]) -> str:
        """Подготовка промпта для объяснения архитектуры"""
        return f"""
Объясни архитектуру проекта понятным языком для разных уровней технической подготовки:

Данные архитектуры:
{json.dumps(architecture_data, indent=2, ensure_ascii=False)}

Предоставь объяснение включающее:
1. Общий обзор архитектуры
2. Основные компоненты и их взаимодействие
3. Преимущества выбранного подхода
4. Потенциальные ограничения
5. Сценарии использования
6. Масштабируемость решения

Объяснение должно быть структурированным и включать как техническую, так и бизнес-перспективу.
"""

    def _prepare_quality_assessment_prompt(self, code_data: Dict[str, Any]) -> str:
        """Подготовка промпта для оценки качества кода"""
        return f"""
Оцени качество кода и предоставь детальную оценку:

Данные о коде:
{json.dumps(code_data, indent=2, ensure_ascii=False)}

Оценка должна включать:
1. Читаемость кода (1-10)
2. Структуру и организацию (1-10)
3. Соответствие стандартам (1-10)
4. Безопасность (1-10)
5. Производительность (1-10)
6. Тестируемость (1-10)
7. Поддерживаемость (1-10)

Предоставь JSON с оценками, общим баллом и детальными комментариями для каждого критерия.
Укажи конкретные области для улучшения.
"""

    def _parse_analysis_response(self, response: str) -> Dict[str, Any]:
        """Парсинг ответа анализа от Claude"""
        try:
            # Попытка извлечь JSON из ответа
            if "```json" in response:
                json_start = response.find("```json") + 7
                json_end = response.find("```", json_start)
                json_str = response[json_start:json_end].strip()
                return json.loads(json_str)
            elif "{" in response and "}" in response:
                json_start = response.find("{")
                json_end = response.rfind("}") + 1
                json_str = response[json_start:json_end]
                return json.loads(json_str)
            else:
                # Если JSON не найден, возвращаем текстовый ответ
                return {"raw_analysis": response}
        except Exception as e:
            logger.warning(f"Failed to parse Claude response as JSON: {e}")
            return {"raw_analysis": response}

    def _parse_recommendations_response(self, response: str) -> Dict[str, Any]:
        """Парсинг ответа рекомендаций от Claude"""
        return self._parse_analysis_response(response)  # Аналогичная логика

    def _parse_quality_response(self, response: str) -> Dict[str, Any]:
        """Парсинг ответа оценки качества от Claude"""
        return self._parse_analysis_response(response)  # Аналогичная логика

    async def health_check(self) -> Dict[str, Any]:
        """Проверка работоспособности Anthropic сервиса"""
        if not self.client:
            return {
                "status": "unavailable",
                "reason": "API key not configured",
                "timestamp": datetime.now().isoformat()
            }

        try:
            # Простой тест API
            message = self.client.messages.create(
                model="claude-3-sonnet-20240229",
                max_tokens=50,
                messages=[
                    {
                        "role": "user",
                        "content": "Respond with 'API working' if you can see this message."
                    }
                ]
            )

            response = message.content[0].text

            return {
                "status": "healthy",
                "response": response,
                "timestamp": datetime.now().isoformat(),
                "model": "claude-3-sonnet-20240229"
            }

        except Exception as e:
            logger.error(f"Anthropic health check failed: {e}")
            return {
                "status": "error",
                "error": str(e),
                "timestamp": datetime.now().isoformat()
            }

# Глобальный экземпляр сервиса
anthropic_service = AnthropicService()