/**
 * Автоматически сгенерированные тесты для seh-endpoints
 * Generated by NASH 4.0 Test Generator
 */

import { jest } from '@jest/globals';

import { getDashboardGrantBurnRate, getDashboardOutcomeVsTarget, getDashboardBCMReadiness } from '../src/api/seh-endpoints.js';

describe('seh-endpoints', () => {

    describe('getDashboardGrantBurnRate', () => {
        test('should be defined', () => {
            expect(getDashboardGrantBurnRate).toBeDefined();
            expect(typeof getDashboardGrantBurnRate).toBe('function');
        });

        test('should handle valid input', async () => {
            await expect(getDashboardGrantBurnRate({})).resolves.not.toThrow();
        });

        test('should handle invalid input', async () => {
            await expect(getDashboardGrantBurnRate(null)).rejects.toThrow();
        });
    });

    describe('getDashboardOutcomeVsTarget', () => {
        test('should be defined', () => {
            expect(getDashboardOutcomeVsTarget).toBeDefined();
            expect(typeof getDashboardOutcomeVsTarget).toBe('function');
        });

        test('should handle valid input', async () => {
            await expect(getDashboardOutcomeVsTarget({})).resolves.not.toThrow();
        });

        test('should handle invalid input', async () => {
            await expect(getDashboardOutcomeVsTarget(null)).rejects.toThrow();
        });
    });

    describe('getDashboardBCMReadiness', () => {
        test('should be defined', () => {
            expect(getDashboardBCMReadiness).toBeDefined();
            expect(typeof getDashboardBCMReadiness).toBe('function');
        });

        test('should handle valid input', async () => {
            await expect(getDashboardBCMReadiness({})).resolves.not.toThrow();
        });

        test('should handle invalid input', async () => {
            await expect(getDashboardBCMReadiness(null)).rejects.toThrow();
        });
    });
});
