#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const os = require('os');
const { spawn, exec } = require('child_process');

// Helper functions to replace fs-extra
const ensureDir = async (dirPath) => {
  try {
    await fs.promises.mkdir(dirPath, { recursive: true });
  } catch (error) {
    if (error.code !== 'EEXIST') throw error;
  }
};

const pathExists = async (filePath) => {
  try {
    await fs.promises.access(filePath);
    return true;
  } catch {
    return false;
  }
};

const readFile = fs.promises.readFile;
const writeFile = fs.promises.writeFile;

class LocalDocumentatorInstaller {
  constructor() {
    this.platform = process.platform;
    this.homeDir = os.homedir();
    this.claudeConfigPath = this.getClaudeConfigPath();
    this.scriptDir = path.dirname(__filename);
  }

  getClaudeConfigPath() {
    switch (this.platform) {
      case 'win32':
        return path.join(process.env.APPDATA, 'Claude', 'claude_desktop_config.json');
      case 'darwin':
        return path.join(this.homeDir, 'Library', 'Application Support', 'Claude', 'claude_desktop_config.json');
      case 'linux':
        return path.join(this.homeDir, '.config', 'claude', 'claude_desktop_config.json');
      default:
        throw new Error(`Unsupported platform: ${this.platform}`);
    }
  }

  async checkNodeJs() {
    return new Promise((resolve) => {
      exec('node --version', (error, stdout) => {
        if (error) {
          console.log('❌ Node.js not found. Please install Node.js first: https://nodejs.org/');
          resolve(false);
        } else {
          console.log(`✅ Node.js found: ${stdout.trim()}`);
          resolve(true);
        }
      });
    });
  }

  async buildLocal() {
    console.log('🔨 Building Documentator locally...');
    
    return new Promise((resolve, reject) => {
      const npm = spawn('npm', ['run', 'build'], {
        stdio: 'inherit',
        cwd: this.scriptDir
      });

      npm.on('close', (code) => {
        if (code === 0) {
          console.log('✅ Documentator built successfully');
          resolve();
        } else {
          console.log('❌ Failed to build Documentator');
          reject(new Error('Build failed'));
        }
      });
    });
  }

  async setupProjects() {
    console.log('📁 Setting up projects directory...');
    
    const projectsDir = path.join(this.homeDir, 'projects');
    await ensureDir(projectsDir);
    
    const exampleDir = path.join(projectsDir, 'example-reports');
    await ensureDir(exampleDir);
    
    const exampleTemplate = `# {{title}}

**Author:** {{author}}
**Date:** {{date|{{new Date().toLocaleDateString()}}}}

## Content

{{content|Main content goes here}}

## Conclusions

{{conclusions|Conclusions will be added later}}

---
*Generated by Documentator*`;

    await writeFile(path.join(exampleDir, 'simple-report.md'), exampleTemplate);
    
    console.log(`✅ Created projects directory: ${projectsDir}`);
    console.log('✅ Added example project with template');
  }

  async configureClaudeDesktop() {
    console.log('⚙️  Configuring Claude Desktop...');
    
    const configDir = path.dirname(this.claudeConfigPath);
    await ensureDir(configDir);
    
    let config = {};
    
    // Read existing config if it exists
    if (await pathExists(this.claudeConfigPath)) {
      try {
        const configContent = await readFile(this.claudeConfigPath, 'utf8');
        config = JSON.parse(configContent);
      } catch (error) {
        console.log('⚠️  Warning: Could not parse existing Claude config, creating new one');
      }
    }
    
    // Ensure mcpServers exists
    if (!config.mcpServers) {
      config.mcpServers = {};
    }
    
    // Add documentator with full path to local build
    const documentatorPath = path.join(this.scriptDir, 'dist', 'index.js');
    config.mcpServers.documentator = {
      command: "node",
      args: [documentatorPath]
    };
    
    // Write back to file
    await writeFile(
      this.claudeConfigPath, 
      JSON.stringify(config, null, 2)
    );
    
    console.log(`✅ Updated Claude Desktop config: ${this.claudeConfigPath}`);
    console.log(`✅ Using local Documentator at: ${documentatorPath}`);
  }

  async restartClaudeDesktop() {
    console.log('🔄 Attempting to restart Claude Desktop...');
    
    try {
      if (this.platform === 'win32') {
        // Windows
        exec('taskkill /F /IM "Claude.exe" 2>nul');
        setTimeout(() => {
          exec('start "" "Claude"', (error) => {
            if (!error) console.log('✅ Claude Desktop restarted');
          });
        }, 2000);
      } else if (this.platform === 'darwin') {
        // macOS
        exec('killall "Claude" 2>/dev/null');
        setTimeout(() => {
          exec('open -a "Claude"', (error) => {
            if (!error) console.log('✅ Claude Desktop restarted');
          });
        }, 2000);
      } else {
        // Linux
        exec('pkill -f claude 2>/dev/null');
        setTimeout(() => {
          exec('claude-desktop 2>/dev/null &', (error) => {
            if (!error) console.log('✅ Claude Desktop restarted');
          });
        }, 2000);
      }
    } catch (error) {
      console.log('⚠️  Could not automatically restart Claude Desktop');
      console.log('   Please restart it manually for changes to take effect');
    }
  }

  async install() {
    try {
      console.log('🚀 Documentator Local Installer');
      console.log('================================\n');
      
      // Step 1: Check Node.js
      const hasNode = await this.checkNodeJs();
      if (!hasNode) {
        return;
      }
      
      // Step 2: Build locally
      await this.buildLocal();
      
      // Step 3: Setup projects
      await this.setupProjects();
      
      // Step 4: Configure Claude Desktop
      await this.configureClaudeDesktop();
      
      // Step 5: Restart Claude Desktop
      await this.restartClaudeDesktop();
      
      console.log('\n🎉 Local Installation Complete!');
      console.log('===============================');
      console.log('');
      console.log('✅ Documentator is built and configured');
      console.log('✅ Projects directory created');
      console.log('✅ Claude Desktop configured');
      console.log('');
      console.log('🧪 Test it out:');
      console.log('  1. Open Claude Desktop');
      console.log('  2. Type: "Show me all my projects"');
      console.log('  3. Type: "Analyze project example-reports"');
      console.log('');
      console.log('📁 Your projects are in:', path.join(this.homeDir, 'projects'));
      console.log('');
      console.log('Happy documenting! 🚀');
      
    } catch (error) {
      console.error('\n❌ Installation failed:', error.message);
      console.log('\n🛠️  Manual steps:');
      console.log('   1. npm run build');
      console.log('   2. Create ~/projects/ directory');
      console.log('   3. Add to Claude Desktop config manually');
      process.exit(1);
    }
  }
}

// Run installer if called directly
if (require.main === module) {
  const installer = new LocalDocumentatorInstaller();
  installer.install();
}

module.exports = LocalDocumentatorInstaller;