#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const os = require('os');
const { exec } = require('child_process');

// Helper functions
const ensureDir = async (dirPath) => {
  try {
    await fs.promises.mkdir(dirPath, { recursive: true });
  } catch (error) {
    if (error.code !== 'EEXIST') throw error;
  }
};

const pathExists = async (filePath) => {
  try {
    await fs.promises.access(filePath);
    return true;
  } catch {
    return false;
  }
};

const readFile = fs.promises.readFile;
const writeFile = fs.promises.writeFile;

class SimpleInstaller {
  constructor() {
    this.platform = process.platform;
    this.homeDir = os.homedir();
    this.claudeConfigPath = this.getClaudeConfigPath();
    this.scriptDir = path.dirname(__filename);
  }

  getClaudeConfigPath() {
    switch (this.platform) {
      case 'win32':
        return path.join(process.env.APPDATA, 'Claude', 'claude_desktop_config.json');
      case 'darwin':
        return path.join(this.homeDir, 'Library', 'Application Support', 'Claude', 'claude_desktop_config.json');
      case 'linux':
        return path.join(this.homeDir, '.config', 'claude', 'claude_desktop_config.json');
      default:
        throw new Error(`Unsupported platform: ${this.platform}`);
    }
  }

  async checkPrerequisites() {
    console.log('🔍 Checking prerequisites...');
    
    // Check Node.js
    const hasNode = await new Promise((resolve) => {
      exec('node --version', (error, stdout) => {
        if (error) {
          console.log('❌ Node.js not found. Please install Node.js first: https://nodejs.org/');
          resolve(false);
        } else {
          console.log(`✅ Node.js found: ${stdout.trim()}`);
          resolve(true);
        }
      });
    });

    if (!hasNode) return false;

    // Check if dist directory exists (built version)
    const distPath = path.join(this.scriptDir, 'dist', 'index.js');
    if (await pathExists(distPath)) {
      console.log('✅ Built version found');
      return true;
    } else {
      console.log('⚠️  Built version not found. Need to build first.');
      console.log('   Run: npm install && npm run build');
      return false;
    }
  }

  async setupProjects() {
    console.log('📁 Setting up projects directory...');
    
    const projectsDir = path.join(this.homeDir, 'projects');
    await ensureDir(projectsDir);
    
    const exampleDir = path.join(projectsDir, 'example-reports');
    await ensureDir(exampleDir);
    
    const exampleTemplate = `# {{title}}

**Author:** {{author}}
**Date:** {{date|{{new Date().toLocaleDateString()}}}}

## Content

{{content|Main content goes here}}

## Conclusions

{{conclusions|Conclusions will be added later}}

---
*Generated by Documentator*`;

    await writeFile(path.join(exampleDir, 'simple-report.md'), exampleTemplate);
    
    console.log(`✅ Created projects directory: ${projectsDir}`);
    console.log('✅ Added example project with template');
  }

  async configureClaudeDesktop() {
    console.log('⚙️  Configuring Claude Desktop...');
    
    const configDir = path.dirname(this.claudeConfigPath);
    await ensureDir(configDir);
    
    let config = {};
    
    // Read existing config if it exists
    if (await pathExists(this.claudeConfigPath)) {
      try {
        const configContent = await readFile(this.claudeConfigPath, 'utf8');
        config = JSON.parse(configContent);
      } catch (error) {
        console.log('⚠️  Warning: Could not parse existing Claude config, creating new one');
      }
    }
    
    // Ensure mcpServers exists
    if (!config.mcpServers) {
      config.mcpServers = {};
    }
    
    // Add documentator with full path to local build
    const documentatorPath = path.join(this.scriptDir, 'dist', 'index.js');
    config.mcpServers.documentator = {
      command: "node",
      args: [documentatorPath]
    };
    
    // Write back to file
    await writeFile(
      this.claudeConfigPath, 
      JSON.stringify(config, null, 2)
    );
    
    console.log(`✅ Updated Claude Desktop config: ${this.claudeConfigPath}`);
    console.log(`✅ Using Documentator at: ${documentatorPath}`);
  }

  async install() {
    try {
      console.log('🚀 Documentator Simple Installer');
      console.log('=================================\n');
      
      // Step 1: Check prerequisites
      const ready = await this.checkPrerequisites();
      if (!ready) {
        return;
      }
      
      // Step 2: Setup projects
      await this.setupProjects();
      
      // Step 3: Configure Claude Desktop
      await this.configureClaudeDesktop();
      
      console.log('\n🎉 Installation Complete!');
      console.log('=========================');
      console.log('');
      console.log('✅ Documentator is configured');
      console.log('✅ Projects directory created');
      console.log('✅ Claude Desktop configured');
      console.log('');
      console.log('🔄 Next steps:');
      console.log('  1. Restart Claude Desktop');
      console.log('  2. Type: "Show me all my projects"');
      console.log('  3. Type: "Analyze project example-reports"');
      console.log('');
      console.log('📁 Your projects are in:', path.join(this.homeDir, 'projects'));
      console.log('');
      console.log('Happy documenting! 🚀');
      
    } catch (error) {
      console.error('\n❌ Installation failed:', error.message);
      console.log('\n🛠️  Manual steps:');
      console.log('   1. Run: npm install && npm run build');
      console.log('   2. Create ~/projects/ directory with example files');
      console.log('   3. Add configuration to Claude Desktop config manually');
      process.exit(1);
    }
  }
}

// Run installer if called directly
if (require.main === module) {
  const installer = new SimpleInstaller();
  installer.install();
}

module.exports = SimpleInstaller;