#!/usr/bin/env python3
"""
Test Generator - Автоматическая генерация тестов на основе AST анализа
"""

import json
from pathlib import Path
from typing import Dict, List
from jinja2 import Template


class TestGenerator:
    def __init__(self, reports_dir: str = "tools/reports", output_dir: str = "tests/generated"):
        self.reports_dir = Path(reports_dir)
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

        self.ast_data = None
        self._load_data()

    def _load_data(self):
        """Загрузить AST анализ"""
        ast_file = self.reports_dir / "ast_analysis.json"
        if ast_file.exists():
            with open(ast_file) as f:
                self.ast_data = json.load(f)

    def generate_all_tests(self):
        """Генерировать тесты для всех сервисов"""
        if not self.ast_data:
            print("❌ No AST data. Run AST analyzer first!")
            return

        print("🧪 Generating tests...\n")

        # Группировать эндпоинты по сервисам
        services = self._group_by_service()

        for service_name, endpoints in services.items():
            self._generate_service_tests(service_name, endpoints)

        # Генерировать Tavern scenarios
        self._generate_tavern_scenarios(services)

        print("\n🎉 Test generation complete!")

    def _group_by_service(self) -> Dict[str, List]:
        """Группировать эндпоинты по сервисам"""
        services = {}

        for endpoint in self.ast_data['endpoints']:
            file_parts = Path(endpoint['file']).parts
            if 'validation-service' in file_parts:
                service_name = 'validation'
            elif 'documents-service' in file_parts:
                service_name = 'documents'
            elif 'governance-service' in file_parts:
                service_name = 'governance'
            elif 'incident-service' in file_parts:
                service_name = 'incident'
            else:
                service_name = 'other'

            if service_name not in services:
                services[service_name] = []

            services[service_name].append(endpoint)

        return services

    def _generate_service_tests(self, service_name: str, endpoints: List[Dict]):
        """Генерировать pytest тесты для сервиса"""
        template = Template('''#!/usr/bin/env python3
"""
Auto-generated tests for {{ service_name }} service
Generated by Test Generator
"""

import pytest
from httpx import AsyncClient
from fastapi import status


BASE_URL = "http://localhost:{{ port }}"


@pytest.fixture
async def client():
    """HTTP клиент для тестов"""
    async with AsyncClient(base_url=BASE_URL) as ac:
        yield ac


{% for endpoint in endpoints %}
@pytest.mark.asyncio
async def test_{{ endpoint.function }}(client: AsyncClient):
    """Test {{ endpoint.method }} {{ endpoint.path }}"""
    {% if endpoint.method == 'GET' %}
    response = await client.get("{{ endpoint.path }}")
    {% elif endpoint.method == 'POST' %}
    test_data = {}  # TODO: Add test data
    response = await client.post("{{ endpoint.path }}", json=test_data)
    {% elif endpoint.method == 'PUT' %}
    test_data = {}  # TODO: Add test data
    response = await client.put("{{ endpoint.path }}", json=test_data)
    {% elif endpoint.method == 'DELETE' %}
    response = await client.delete("{{ endpoint.path }}")
    {% endif %}

    # TODO: Add assertions based on expected behavior
    assert response.status_code in [200, 201, 204, 404]


{% endfor %}

# TODO: Add additional test cases:
# - Error handling (400, 404, 500)
# - Authentication/Authorization
# - Edge cases
# - Data validation
''')

        # Определить порт сервиса
        ports = {
            'validation': 8022,
            'documents': 8024,
            'governance': 8020,
            'incident': 8025
        }
        port = ports.get(service_name, 8000)

        # Заменить {id} на конкретные значения для тестов
        processed_endpoints = []
        for endpoint in endpoints:
            processed = endpoint.copy()
            # Заменить path parameters на тестовые значения
            processed['path'] = endpoint['path'].replace('{', '1')  # Простая замена
            processed['path'] = processed['path'].replace('}', '')
            processed_endpoints.append(processed)

        content = template.render(
            service_name=service_name.title(),
            port=port,
            endpoints=processed_endpoints
        )

        output_file = self.output_dir / f"test_{service_name}_api.py"
        with open(output_file, 'w') as f:
            f.write(content)

        print(f"✅ {service_name}: {output_file} ({len(endpoints)} tests)")

    def _generate_tavern_scenarios(self, services: Dict):
        """Генерировать Tavern test scenarios (YAML)"""
        for service_name, endpoints in services.items():
            template = Template('''---
# Tavern API Test Scenarios for {{ service_name }} service
# Generated by Test Generator

test_name: {{ service_name }}_api_test_suite

stages:
{% for endpoint in endpoints %}
  - name: Test {{ endpoint.method }} {{ endpoint.path }}
    request:
      url: "{base_url}{{ endpoint.path }}"
      method: {{ endpoint.method }}
      {% if endpoint.method in ['POST', 'PUT'] %}
      json:
        # TODO: Add test data
        test: true
      {% endif %}
    response:
      status_code: 200
      # TODO: Add response validation

{% endfor %}
''')

            content = template.render(
                service_name=service_name.title(),
                endpoints=endpoints[:5]  # Первые 5 для примера
            )

            output_file = self.output_dir / f"tavern_test_{service_name}.yaml"
            with open(output_file, 'w') as f:
                f.write(content)

            print(f"✅ Tavern: {output_file}")

    def generate_unit_tests(self):
        """Генерировать unit тесты для сервисных классов"""
        if not self.ast_data:
            return

        print("\n🔬 Generating unit tests...\n")

        # Группировать классы по файлам
        classes_by_file = {}
        for cls in self.ast_data['classes']:
            file_path = cls['file']
            if 'service' in file_path.lower():  # Только service классы
                if file_path not in classes_by_file:
                    classes_by_file[file_path] = []
                classes_by_file[file_path].append(cls)

        template = Template('''#!/usr/bin/env python3
"""
Auto-generated unit tests for {{ file_name }}
Generated by Test Generator
"""

import pytest
from unittest.mock import Mock, AsyncMock, patch


{% for cls in classes %}
class Test{{ cls.name }}:
    """Tests for {{ cls.name }}"""

    @pytest.fixture
    def {{ cls.name.lower() }}(self):
        """Create {{ cls.name }} instance for testing"""
        # TODO: Add proper initialization
        mock_repository = Mock()
        return {{ cls.name }}(mock_repository)

    {% for method in cls.methods %}
    {% if not method.startswith('_') %}
    @pytest.mark.asyncio
    async def test_{{ method }}(self, {{ cls.name.lower() }}):
        """Test {{ cls.name }}.{{ method }}()"""
        # TODO: Add test implementation
        pass

    {% endif %}
    {% endfor %}

{% endfor %}
''')

        for file_path, classes in list(classes_by_file.items())[:3]:  # Первые 3 файла
            file_name = Path(file_path).stem
            content = template.render(
                file_name=file_name,
                classes=classes
            )

            output_file = self.output_dir / f"test_{file_name}_unit.py"
            with open(output_file, 'w') as f:
                f.write(content)

            print(f"✅ Unit tests: {output_file}")

    def generate_pytest_config(self):
        """Генерировать pytest.ini и conftest.py"""
        pytest_ini = '''[pytest]
testpaths = tests/generated
python_files = test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = auto
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    integration: marks tests as integration tests
    unit: marks tests as unit tests
'''

        conftest = '''"""
Global pytest configuration
"""

import pytest
import asyncio


@pytest.fixture(scope="session")
def event_loop():
    """Create event loop for async tests"""
    loop = asyncio.get_event_loop_policy().new_event_loop()
    yield loop
    loop.close()


@pytest.fixture
def tenant_id():
    """Default tenant ID for tests"""
    return "test-tenant-123"


@pytest.fixture
def user_id():
    """Default user ID for tests"""
    return "test-user-456"
'''

        # pytest.ini
        pytest_file = self.output_dir.parent / "pytest.ini"
        with open(pytest_file, 'w') as f:
            f.write(pytest_ini)
        print(f"\n✅ Config: {pytest_file}")

        # conftest.py
        conftest_file = self.output_dir / "conftest.py"
        with open(conftest_file, 'w') as f:
            f.write(conftest)
        print(f"✅ Config: {conftest_file}")

    def generate_requirements_test(self):
        """Генерировать requirements-test.txt"""
        requirements = '''# Testing dependencies
pytest>=7.4.0
pytest-asyncio>=0.21.0
pytest-cov>=4.1.0
pytest-mock>=3.11.0
httpx>=0.24.0
tavern>=2.0.0
faker>=19.0.0
'''

        output_file = self.output_dir.parent / "requirements-test.txt"
        with open(output_file, 'w') as f:
            f.write(requirements)
        print(f"✅ Requirements: {output_file}")


if __name__ == "__main__":
    generator = TestGenerator()
    generator.generate_all_tests()
    generator.generate_unit_tests()
    generator.generate_pytest_config()
    generator.generate_requirements_test()

    print("\n📝 Generated test files:")
    print("   - tests/generated/test_*_api.py (API integration tests)")
    print("   - tests/generated/test_*_unit.py (Unit tests)")
    print("   - tests/generated/tavern_test_*.yaml (Tavern scenarios)")
    print("   - tests/pytest.ini (pytest configuration)")
    print("   - tests/requirements-test.txt (test dependencies)")

    print("\n🚀 Run tests:")
    print("   pip install -r tests/requirements-test.txt")
    print("   pytest tests/generated/ -v")
    print("   pytest tests/generated/ --cov=platform-services")
