
  expertise_center:
    type: service
    location: intelligent-core/expertise-center
    port: null
    technology:
      - Python 3.11
      - FastAPI
    dependencies:
      infrastructure:

      external:

      internal:
        - ai_foundation
        - ai_foundation/expertise_center
        - shared/base
    endpoints:

    metrics:
      loc: 7932
      files: 45
      classes: 47
      functions: 8
    status: discovered
