from odoo import models, fields, api, _
from odoo.exceptions import UserError

class BcmKnowledgeArticle(models.Model):
    _name = 'bcm.knowledge.article'
    _description = 'BCM Knowledge Article'
    _inherit = ['mail.thread', 'mail.activity.mixin']

    name = fields.Char('Article Title', required=True, tracking=True)
    summary = fields.Text('Summary')
    content = fields.Html('Content', required=True)

    # Article metadata
    article_type = fields.Selection([
        ('guide', 'How-to Guide'),
        ('best_practice', 'Best Practice'),
        ('case_study', 'Case Study'),
        ('template', 'Template'),
        ('faq', 'FAQ'),
        ('policy', 'Policy Document'),
        ('ai_generated', 'AI Generated Content'),
        ('community_driven', 'Community Driven')
    ], required=True, default='guide')

    # Publishing
    is_published = fields.Boolean('Published', default=False, tracking=True)

    # Knowledge management
    tags = fields.Many2many('bcm.knowledge.tag', string='Tags')
    category_id = fields.Many2one('bcm.knowledge.category', 'Category')
    iso_clause_id = fields.Many2one('bcm.iso.clause', 'Related ISO Clause')
    iso_clauses = fields.Many2many('bcm.iso.clause', string='ISO Clauses')
    sequence = fields.Integer('Sequence', default=10)

    # AI fields
    ai_prompt = fields.Text('AI Generation Prompt', readonly=True)
    ai_confidence = fields.Float('AI Confidence', readonly=True, default=0.0)

    # Relations
    related_scenarios = fields.Many2many('bcm.scenario', string='Related Scenarios')
    related_templates = fields.Many2many('bcm.template', string='Related Templates')
    parent_article_id = fields.Many2one('bcm.knowledge.article', 'Parent Article')
    child_article_ids = fields.One2many('bcm.knowledge.article', 'parent_article_id', 'Child Articles')

    # Computed metrics
    bookmark_count = fields.Integer('Bookmark Count', compute='_compute_bookmark_count')
    feedback_count = fields.Integer('Feedback Count', default=0)

    # Status and workflow
    status = fields.Selection([
        ('draft', 'Draft'),
        ('review', 'Under Review'),
        ('published', 'Published'),
        ('archived', 'Archived')
    ], default='draft', tracking=True)

    # Metrics
    view_count = fields.Integer('Views', default=0)
    rating = fields.Float('Rating', default=0.0)
    rating_count = fields.Integer('Rating Count', default=0)
    usefulness_score = fields.Float('Usefulness Score', default=0.0, compute='_compute_usefulness_score', store=True)

    # Expert verification
    is_expert_verified = fields.Boolean('Expert Verified', default=False)
    verified_by = fields.Many2one('res.users', 'Verified By')
    verification_date = fields.Datetime('Verification Date')

    # Relations
    author_id = fields.Many2one('res.users', 'Author', required=True, default=lambda self: self.env.user)

    # Source relations (for articles generated from other modules)
    source_exercise_id = fields.Many2one('bcm.exercise', 'Source Exercise', readonly=True)
    source_scenario_id = fields.Many2one('bcm.scenario', 'Source Scenario', readonly=True)
    source_forum_topic_id = fields.Many2one('bcm.forum.topic', 'Source Forum Topic', readonly=True)

    # Multi-tenancy
    company_id = fields.Many2one('res.company', required=True, default=lambda self: self.env.company)

    def action_regenerate_with_ai(self):
        """Regenerate article content using AI"""
        if self.article_type != 'ai_generated':
            raise UserError(_("AI regeneration is only available for AI-generated articles."))

        try:
            # This would call the AI service to regenerate content
            # For now, we'll just add a placeholder
            updated_content = self.content + "\n\n<!-- Content regenerated by AI -->"

            self.write({
                'content': updated_content,
                'summary': "AI-regenerated content"
            })

            return {
                'type': 'ir.actions.client',
                'tag': 'display_notification',
                'params': {
                    'title': _('AI Regeneration Complete'),
                    'message': _('Article content has been regenerated using AI.'),
                    'type': 'success',
                }
            }
        except Exception as e:
            raise UserError(_('AI regeneration failed: %s') % str(e))

    def website_publish_button(self):
        """Publish article to website"""
        self.write({
            'is_published': True,
            'status': 'published'
        })

        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('Article Published'),
                'message': _('The article has been published to the website.'),
                'type': 'success',
            }
        }

    @api.depends('rating', 'view_count', 'rating_count')
    def _compute_usefulness_score(self):
        """Compute usefulness score based on rating and views"""
        for article in self:
            if article.rating_count > 0 and article.view_count > 0:
                # Simple formula: (rating * rating_count + view_count/10) / 2
                article.usefulness_score = min(10.0, (article.rating * article.rating_count + article.view_count / 10.0) / 2.0)
            else:
                article.usefulness_score = 0.0

    def _compute_bookmark_count(self):
        """Compute number of bookmarks for this article"""
        for article in self:
            article.bookmark_count = self.env['bcm.knowledge.bookmark'].search_count([
                ('article_id', '=', article.id)
            ])


class BcmKnowledgeTag(models.Model):
    _name = 'bcm.knowledge.tag'
    _description = 'Knowledge Tag'

    name = fields.Char('Tag Name', required=True)
    color = fields.Integer('Color', default=0)
    description = fields.Text('Description')
    usage_count = fields.Integer('Usage Count', default=0)
    article_count = fields.Integer('Article Count', compute='_compute_article_count')

    company_id = fields.Many2one('res.company', required=True, default=lambda self: self.env.company)

    def _compute_article_count(self):
        """Compute number of articles using this tag"""
        for tag in self:
            tag.article_count = self.env['bcm.knowledge.article'].search_count([
                ('tags', 'in', tag.id)
            ])


class BcmKnowledgeCategory(models.Model):
    _name = 'bcm.knowledge.category'
    _description = 'Knowledge Category'

    name = fields.Char('Category Name', required=True)
    description = fields.Text('Description')
    parent_id = fields.Many2one('bcm.knowledge.category', 'Parent Category')
    child_ids = fields.One2many('bcm.knowledge.category', 'parent_id', 'Subcategories')

    company_id = fields.Many2one('res.company', required=True, default=lambda self: self.env.company)


class BcmIsoClause(models.Model):
    _name = 'bcm.iso.clause'
    _description = 'ISO 22301 Clause'

    name = fields.Char('Clause Number', required=True)
    title = fields.Char('Clause Title', required=True)
    description = fields.Text('Description')

    # ISO structure
    section = fields.Selection([
        ('4', 'Context of the organization'),
        ('5', 'Leadership'),
        ('6', 'Planning'),
        ('7', 'Support'),
        ('8', 'Operation'),
        ('9', 'Performance evaluation'),
        ('10', 'Improvement')
    ])

    # Computed fields
    article_count = fields.Integer('Article Count', compute='_compute_article_count')

    company_id = fields.Many2one('res.company', required=True, default=lambda self: self.env.company)

    def _compute_article_count(self):
        """Compute number of articles for this ISO clause"""
        for clause in self:
            clause.article_count = self.env['bcm.knowledge.article'].search_count([
                '|',
                ('iso_clause_id', '=', clause.id),
                ('iso_clauses', 'in', clause.id)
            ])


class BcmKnowledgeBookmark(models.Model):
    _name = 'bcm.knowledge.bookmark'
    _description = 'Knowledge Bookmark'

    article_id = fields.Many2one('bcm.knowledge.article', 'Article', required=True)
    user_id = fields.Many2one('res.users', 'User', required=True, default=lambda self: self.env.user)
    created_at = fields.Datetime('Created', default=fields.Datetime.now)

    company_id = fields.Many2one('res.company', required=True, default=lambda self: self.env.company)


class BcmExpertVerification(models.Model):
    _name = 'bcm.expert.verification'
    _description = 'Expert Verification'

    article_id = fields.Many2one('bcm.knowledge.article', 'Article', required=True)
    expert_id = fields.Many2one('res.users', 'Expert', required=True)

    verification_status = fields.Selection([
        ('pending', 'Pending'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected')
    ], default='pending')

    confidence_score = fields.Float('Confidence Score', default=0.0)
    comments = fields.Text('Comments')
    verification_date = fields.Datetime('Verification Date')

    company_id = fields.Many2one('res.company', required=True, default=lambda self: self.env.company)