# -*- coding: utf-8 -*-

from odoo import models, fields, api, _
from odoo.exceptions import ValidationError, AccessError
import json
import logging

_logger = logging.getLogger(__name__)

class BcmScenario(models.Model):
    _name = 'bcm.scenario'
    _description = 'BCM Scenario for Community Hub'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _order = 'create_date desc'
    _rec_name = 'title'
    
    # Основная информация согласно ТЗ
    title = fields.Char(
        string='Scenario Title',
        required=True, index=True,
        tracking=True,
        help='Title of the scenario'
    )
    
    category = fields.Selection([
        ('epidemic', 'Epidemic/Pandemic'),
        ('blackout', 'Power Blackout'),
        ('cyber', 'Cyber Security Incident'),
        ('supply', 'Supply Chain Disruption'),
        ('natural', 'Natural Disaster'),
        ('terrorism', 'Terrorism/Security'),
        ('financial', 'Financial Crisis'),
        ('other', 'Other')
    ], string='Category', required=True, tracking=True)
    
    tags = fields.Many2many(
        'bcm.tag',
        string='Tags',
        help='Tags for scenario categorization'
    )
    
    level = fields.Selection([
        ('tabletop', 'Tabletop Exercise'),
        ('full', 'Full Simulation')
    ], string='Exercise Level', required=True, default='tabletop')
    
    domains = fields.Many2many(
        'bcm.domain',
        string='Applicable Domains',
        help='Business domains this scenario applies to (IT/clinic/logistics etc.)'
    )
    
    # Контент сценария
    content_md = fields.Text(
        string='Scenario Content (Markdown)',
        required=True, index=True,
        help='Detailed scenario description and steps in Markdown format'
    )
    
    inputs_schema = fields.Text(
        string='Input Parameters Schema',
        help='JSONSchema for scenario parameters',
        default='{"type": "object", "properties": {}}'
    )
    
    expected_metrics = fields.Text(
        string='Expected Metrics (JSON)',
        help='JSON with expected metrics and outcomes',
        default='{}'
    )
    
    # Лицензирование
    license = fields.Selection([
        ('cc_by_sa', 'Creative Commons BY-SA'),
        ('mit', 'MIT License'),
        ('custom', 'Custom License')
    ], string='License', default='cc_by_sa', required=True)
    
    custom_license_text = fields.Text(
        string='Custom License Text',
        help='Custom license terms if license is "custom"'
    )
    
    # Видимость и права
    visibility = fields.Selection([
        ('public', 'Public'),
        ('private', 'Private'),
        ('client_only', 'Client Only')
    ], string='Visibility', default='public', required=True, tracking=True)
    
    # Авторство
    author_user_id = fields.Many2one(
        'res.users',
        string='Author',
        required=True, index=True,
        default=lambda self: self.env.user
    )
    
    author_org = fields.Char(
        string='Author Organization',
        compute='_compute_author_org',
        store=True
    )
    
    company_id = fields.Many2one(
        'res.company',
        string='Company',
        default=lambda self: self.env.company
    )
    
    # Статус модерации
    status = fields.Selection([
        ('draft', 'Draft'),
        ('pending_review', 'Pending Review'),
        ('published', 'Published'),
        ('rejected', 'Rejected')
    ], string='Status', default='draft', required=True, tracking=True)
    
    rejection_reason = fields.Text(
        string='Rejection Reason',
        help='Reason for rejection if status is rejected'
    )
    
    # Версионирование
    version = fields.Integer(
        string='Version',
        default=1,
        required=True, index=True
    )
    
    parent_id = fields.Many2one(
        'bcm.scenario',
        string='Parent Scenario',
        help='Original scenario if this is a fork'
    )
    
    # Связанные записи
    review_ids = fields.One2many(
        'bcm.scenario.review',
        'scenario_id',
        string='Reviews'
    )
    
    rating_ids = fields.One2many(
        'bcm.scenario.rating',
        'scenario_id',
        string='Ratings'
    )

    # AI Generation metadata (for AI-generated scenarios)
    meta_ai_generated = fields.Boolean(
        string='AI Generated',
        default=False,
        help='Whether this scenario was generated by AI'
    )

    meta_ai_params = fields.Text(
        string='AI Generation Parameters',
        help='JSON parameters used for AI generation'
    )

    # Forum integration
    forum_topic_id = fields.Many2one(
        'bcm.forum.topic',
        string='Forum Discussion',
        help='Related forum discussion topic'
    )

    # Template Integration (NEW)
    available_templates = fields.Many2many(
        'bcm.template',
        string='Compatible Templates',
        compute='_compute_available_templates',
        help='Workflow templates compatible with this scenario'
    )

    exercise_count = fields.Integer(
        'Exercises Created',
        compute='_compute_exercise_count',
        help='Number of exercises created from this scenario'
    )

    def action_publish_scenario(self):
        """Publish scenario and auto-create forum discussion"""
        # Existing publish logic
        self.ensure_one()
        self.is_published = True

        # NEW: Auto-create forum topic
        if not self.forum_topic_id:
            forum_topic = self.env['bcm.forum.topic'].create_from_scenario(self.id)
            if forum_topic:
                self.forum_topic_id = forum_topic.id

        # NEW: Notify Community Service via webhook
        self._notify_community_service_scenario_published()

        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': 'Scenario Published',
                'message': f'Scenario "{self.title}" published with forum discussion created',
                'type': 'success',
            }
        }

    def _notify_community_service_scenario_published(self):
        """Send webhook to Community Service about published scenario"""
        try:
            import requests

            webhook_url = "http://localhost:3000/webhooks/odoo/scenario-published"
            webhook_data = {
                'scenario_id': self.id,
                'scenario_data': {
                    'title': self.title,
                    'category': self.category,
                    'level': self.level,
                    'meta_description': self.meta_description,
                    'meta_duration': self.meta_duration,
                    'meta_participants': self.meta_participants,
                    'meta_ai_generated': self.meta_ai_generated
                },
                'timestamp': self.write_date.isoformat() if self.write_date else None
            }

            response = requests.post(webhook_url, json=webhook_data, timeout=5)
            if response.status_code == 200:
                self.message_post(
                    body="Community Service notified of scenario publication",
                    subject="Community Integration"
                )

        except Exception as e:
            # Don't fail scenario publication if webhook fails
            import logging
            logging.getLogger(__name__).warning(f"Failed to notify Community Service: {e}")

    def action_create_forum_discussion(self):
        """Manual forum discussion creation"""
        if self.forum_topic_id:
            return {
                'type': 'ir.actions.act_url',
                'url': self.forum_topic_id.forum_url or f'http://localhost:3000/topics/{self.forum_topic_id.external_id}',
                'target': 'new',
            }

        # Create new forum topic
        forum_topic = self.env['bcm.forum.topic'].create_from_scenario(self.id)
        if forum_topic:
            self.forum_topic_id = forum_topic.id
            return {
                'type': 'ir.actions.client',
                'tag': 'display_notification',
                'params': {
                    'title': 'Forum Discussion Created',
                    'message': 'Forum discussion topic created successfully',
                    'type': 'success',
                }
            }

    @api.depends('category', 'level')
    def _compute_available_templates(self):
        """Get compatible templates for scenario"""
        for scenario in self:
            # Find workflow templates compatible with scenario type
            domain = [('category', '=', 'workflow')]

            # Match template types to scenario
            template_types = [f'{scenario.level}_exercise']

            if scenario.category in ['cyber', 'terrorism']:
                template_types.append('incident_response')
            if scenario.category == 'natural':
                template_types.append('functional_exercise')

            domain.append(('template_type', 'in', template_types))

            templates = self.env['bcm.template'].search(domain)
            scenario.available_templates = templates

    @api.depends()
    def _compute_exercise_count(self):
        """Count exercises created from this scenario"""
        for scenario in self:
            exercises = self.env['bcm.exercise'].search_count([
                ('scenario_id', '=', scenario.id)
            ])
            scenario.exercise_count = exercises

    def action_create_exercise_from_scenario(self):
        """Create exercise from scenario with template selection"""
        return {
            'type': 'ir.actions.act_window',
            'name': _('Create Exercise from Scenario'),
            'res_model': 'bcm.exercise.creation.wizard',
            'view_mode': 'form',
            'view_type': 'form',
            'target': 'new',
            'context': {
                'default_scenario_id': self.id,
                'default_exercise_name': f'Exercise: {self.title}',
                'default_exercise_type': self.level,
                'available_templates': self.available_templates.ids
            }
        }

    # Вычисляемые поля
    avg_rating = fields.Float(
        compute='_compute_ratings',
        string='Average Rating',
        store=True
    )
    
    rating_count = fields.Integer(
        compute='_compute_ratings',
        string='Number of Ratings',
        store=True
    )
    
    application_count = fields.Integer(
        compute='_compute_application_count',
        string='Times Applied',
        help='Number of times this scenario was applied to clients'
    )
    
    is_author = fields.Boolean(
        compute='_compute_is_author',
        string='Is Author',
        help='Current user is the author of this scenario'
    )
    
    can_edit = fields.Boolean(
        compute='_compute_permissions',
        string='Can Edit'
    )
    
    can_review = fields.Boolean(
        compute='_compute_permissions',
        string='Can Review'
    )
    
    @api.depends('author_user_id')
    def _compute_author_org(self):
        for record in self:
            if record.author_user_id and record.author_user_id.company_id:
                record.author_org = record.author_user_id.company_id.name
            else:
                record.author_org = 'Unknown'
    
    @api.depends('rating_ids.stars')
    def _compute_ratings(self):
        for record in self:
            ratings = record.rating_ids
            if ratings:
                record.avg_rating = sum(ratings.mapped('stars')) / len(ratings)
                record.rating_count = len(ratings)
            else:
                record.avg_rating = 0.0
                record.rating_count = 0
    
    def _compute_application_count(self):
        for record in self:
            # TODO: Подсчет применений через bcm.exercise
            record.application_count = 0
    
    @api.depends('author_user_id')
    def _compute_is_author(self):
        for record in self:
            record.is_author = record.author_user_id == self.env.user
    
    def _compute_permissions(self):
        for record in self:
            # Редактировать может только автор черновиков
            record.can_edit = record.is_author and record.status == 'draft'
            
            # Рецензировать могут только модераторы
            record.can_review = self.env.user.has_group('bcm_scenario_hub.group_scenario_reviewer')
    
    @api.model
    def create(self, vals):
        """Создание сценария с уведомлениями"""
        scenario = super().create(vals)
        
        # Отправить в модерацию если не черновик
        if scenario.visibility == 'public' and scenario.status == 'draft':
            scenario.status = 'pending_review'
            scenario.message_post(
                body=_('Scenario submitted for public review'),
                message_type='notification'
            )
        
        return scenario
    
    def action_submit_for_review(self):
        """Отправить сценарий на модерацию"""
        self.ensure_one()
        
        if self.status != 'draft':
            raise ValidationError(_('Only draft scenarios can be submitted for review'))
        
        if not self.content_md or not self.title:
            raise ValidationError(_('Scenario must have title and content before submission'))
        
        self.status = 'pending_review'
        self.message_post(
            body=_('Scenario submitted for review by %s') % self.env.user.name,
            message_type='notification'
        )
        
        # Уведомить модераторов
        self._notify_reviewers()
    
    def action_approve(self, review_notes=''):
        """Одобрить сценарий (только модераторы)"""
        self.ensure_one()
        
        if not self.env.user.has_group('bcm_scenario_hub.group_scenario_reviewer'):
            raise AccessError(_('Only reviewers can approve scenarios'))
        
        if self.status != 'pending_review':
            raise ValidationError(_('Only scenarios pending review can be approved'))
        
        self.status = 'published'
        
        # Создать запись рецензии
        self.env['bcm.scenario.review'].create({
            'scenario_id': self.id,
            'reviewer_id': self.env.user.id,
            'decision': 'approve',
            'notes': review_notes,
        })
        
        self.message_post(
            body=_('Scenario approved and published by %s') % self.env.user.name,
            message_type='notification'
        )
    
    def action_reject_wizard(self):
        """Открыть мастер отклонения сценария"""
        self.ensure_one()
        
        if not self.env.user.has_group('bcm_scenario_hub.group_scenario_reviewer'):
            raise AccessError(_('Only reviewers can reject scenarios'))
        
        if self.status != 'pending_review':
            raise ValidationError(_('Only scenarios pending review can be rejected'))
        
        # TODO: Implement rejection wizard
        # For now, just reject with a default reason
        return self.action_reject('Rejected by reviewer')
        
    def action_reject(self, rejection_reason):
        """Отклонить сценарий (только модераторы)"""
        self.ensure_one()
        
        if not self.env.user.has_group('bcm_scenario_hub.group_scenario_reviewer'):
            raise AccessError(_('Only reviewers can reject scenarios'))
        
        if self.status != 'pending_review':
            raise ValidationError(_('Only scenarios pending review can be rejected'))
        
        self.write({
            'status': 'rejected',
            'rejection_reason': rejection_reason
        })
        
        # Создать запись рецензии
        self.env['bcm.scenario.review'].create({
            'scenario_id': self.id,
            'reviewer_id': self.env.user.id,
            'decision': 'reject',
            'notes': rejection_reason,
        })
        
        self.message_post(
            body=_('Scenario rejected by %s: %s') % (self.env.user.name, rejection_reason),
            message_type='notification'
        )
    
    def action_fork(self):
        """Создать форк сценария"""
        self.ensure_one()
        
        if self.status != 'published':
            raise ValidationError(_('Only published scenarios can be forked'))
        
        fork_vals = {
            'title': f'{self.title} (Fork)',
            'category': self.category,
            'level': self.level,
            'content_md': self.content_md,
            'inputs_schema': self.inputs_schema,
            'expected_metrics': self.expected_metrics,
            'license': self.license,
            'custom_license_text': self.custom_license_text,
            'visibility': 'private',
            'status': 'draft',
            'parent_id': self.id,
            'version': 1,
            'author_user_id': self.env.user.id,
            'tags': [(6, 0, self.tags.ids)],
            'domains': [(6, 0, self.domains.ids)],
        }
        
        fork = self.create(fork_vals)
        
        return {
            'type': 'ir.actions.act_window',
            'name': _('Forked Scenario'),
            'res_model': 'bcm.scenario',
            'res_id': fork.id,
            'view_mode': 'form',
            'target': 'current'
        }
    
    def action_apply_to_client(self):
        """Применить сценарий к клиенту"""
        self.ensure_one()
        
        if self.status != 'published':
            raise ValidationError(_('Only published scenarios can be applied'))
        
        return {
            'type': 'ir.actions.act_window',
            'name': _('Apply Scenario'),
            'res_model': 'bcm.scenario.apply.wizard',
            'view_mode': 'form',
            'target': 'new',
            'context': {'default_scenario_id': self.id}
        }
    
    def get_inputs_schema_dict(self):
        """Получить схему входных параметров как словарь"""
        self.ensure_one()
        try:
            return json.loads(self.inputs_schema or '{}')
        except json.JSONDecodeError:
            return {}
    
    def get_expected_metrics_dict(self):
        """Получить ожидаемые метрики как словарь"""
        self.ensure_one()
        try:
            return json.loads(self.expected_metrics or '{}')
        except json.JSONDecodeError:
            return {}
    
    def _notify_reviewers(self):
        """Уведомить модераторов о новом сценарии"""
        reviewers = self.env['res.users'].search([
            ('groups_id', 'in', [self.env.ref('bcm_scenario_hub.group_scenario_reviewer').id])
        ])
        
        for reviewer in reviewers:
            self.activity_schedule(
                'bcm_scenario_hub.mail_activity_scenario_review',
                user_id=reviewer.id,
                summary=_('Review scenario: %s') % self.title
            )
    
    @api.model
    def search_scenarios(self, domain=None, **kwargs):
        """Расширенный поиск сценариев с фильтрацией"""
        if domain is None:
            domain = []
        
        # Базовая фильтрация по видимости
        user = self.env.user
        visibility_domain = [
            '|', '|',
            ('visibility', '=', 'public'),
            '&', ('visibility', '=', 'client_only'), ('author_user_id.company_id', '=', user.company_id.id),
            ('author_user_id', '=', user.id)
        ]
        
        domain = domain + visibility_domain + [('status', '=', 'published')]
        
        return self.search(domain, **kwargs)
