/**
 * Автоматически сгенерированные тесты для supabase-webhooks
 * Generated by NASH 4.0 Test Generator
 */

import { jest } from '@jest/globals';

import { verifyWebhookSignature, processWebhookEvent, subscribeToEvent, unsubscribeFromEvent, configureSupabaseWebhooks } from '../src/events/supabase-webhooks.js';

describe('supabase-webhooks', () => {

    describe('verifyWebhookSignature', () => {
        test('should be defined', () => {
            expect(verifyWebhookSignature).toBeDefined();
            expect(typeof verifyWebhookSignature).toBe('function');
        });

        test('should handle valid input', () => {
            expect(() => verifyWebhookSignature({})).not.toThrow();
        });

        test('should handle invalid input', () => {
            expect(() => verifyWebhookSignature(null)).toThrow();
        });
    });

    describe('processWebhookEvent', () => {
        test('should be defined', () => {
            expect(processWebhookEvent).toBeDefined();
            expect(typeof processWebhookEvent).toBe('function');
        });

        test('should handle valid input', async () => {
            await expect(processWebhookEvent({})).resolves.not.toThrow();
        });

        test('should handle invalid input', async () => {
            await expect(processWebhookEvent(null)).rejects.toThrow();
        });
    });

    describe('subscribeToEvent', () => {
        test('should be defined', () => {
            expect(subscribeToEvent).toBeDefined();
            expect(typeof subscribeToEvent).toBe('function');
        });

        test('should handle valid input', () => {
            expect(() => subscribeToEvent({})).not.toThrow();
        });

        test('should handle invalid input', () => {
            expect(() => subscribeToEvent(null)).toThrow();
        });
    });

    describe('unsubscribeFromEvent', () => {
        test('should be defined', () => {
            expect(unsubscribeFromEvent).toBeDefined();
            expect(typeof unsubscribeFromEvent).toBe('function');
        });

        test('should handle valid input', () => {
            expect(() => unsubscribeFromEvent({})).not.toThrow();
        });

        test('should handle invalid input', () => {
            expect(() => unsubscribeFromEvent(null)).toThrow();
        });
    });

    describe('configureSupabaseWebhooks', () => {
        test('should be defined', () => {
            expect(configureSupabaseWebhooks).toBeDefined();
            expect(typeof configureSupabaseWebhooks).toBe('function');
        });

        test('should handle valid input', async () => {
            await expect(configureSupabaseWebhooks({})).resolves.not.toThrow();
        });

        test('should handle invalid input', async () => {
            await expect(configureSupabaseWebhooks(null)).rejects.toThrow();
        });
    });
});
